@startuml

[-> BoardBroker: updateBoard(movement)

BoardBroker -> Board: getPieceAt(movement.source)
alt piece not found
	BoardBroker -->[: false
end

BoardBroker -> MovementPolicy: isLegalMovement(piece.type, movement.source, movement.target)
alt not legal movement
	BoardBroker -->[: false
end

BoardBroker -> Board: isPathClear(movement.source, movement.target)
alt path not clear
	BoardBroker -->[: false
end

BoardBroker -> Board: getPieceAt(movement.target)
alt piece found
	alt pieces of same color
		BoardBroker -->[: false
	else different color
		BoardBroker -> TargetPiece: captured()
		TargetPiece --> BoardBroker: targetMemento
	end
end

BoardBroker -> SourcePiece: move(movement.target)
SourcePiece --> BoardBroker: sourceMemento

BoardBroker -> Board: isKingInCheck()
alt king in check
	BoardBroker -> SourcePiece: restoreTo(sourceMemento)
	BoardBroker -> TargetPiece: restoreTo(targetMemento)
	BoardBroker -->[: false
end

BoardBroker -->[: true

hide footbox
@enduml