@startuml

[-> Player: play()
Player -> Strategy: play(board)
Strategy -> Command: <<create>>

Player -> Command: execute(this)
alt movement command
	Command -> Player: move(command.movement)
	|||
else draw offer command
	Command -> Player: offerDraw()
	|||
else resignation command
	Command -> Player: resign()
	|||
else game ending command
	Command -> Player: endGame(gameResult)
	|||
end

hide footbox
@enduml