@startuml

== Move ==
Game -> Player : yourTurn()
Player -> Strategy : nextAction()
Player <-- Strategy : move
Player -> Board : move(from, to)
Player <-- Board : true
Game <-- Player : true

== Invalid Move ==
Game -> Player : yourTurn()
Player -> Strategy : nextAction()
Player <-- Strategy : move
Player -> Board : move(from, to)
Player <-- Board : false
Player -> Strategy : actionRejected(move)
Game <-- Player : true

== Draw Offer Rejected ==
Game -> Player : yourTurn()
Player -> Strategy : nextAction()
Player <-- Strategy : drawOffer

Player -> Opponent : acceptDraw()
Player <-- Opponent : false

Player -> Strategy : actionRejected(drawOffer)
Game <-- Player : true

== Rule Claim Rejected ==
Game -> Player : yourTurn()
Player -> Strategy : nextAction()
Player <-- Strategy : ruleClaim

Player -> Player : verifyThreefoldClaim()

Player -> Strategy : actionRejected(ruleClaim)
Game <-- Player : true

== Resignation ==
Game -> Player : yourTurn()
Player -> Strategy : nextAction()
Player <-- Strategy : resignation
Game <-- Player : false


hide footbox
@enduml